import Navbar from "@/components/sections/Navbar";
import "./globals.css";
import Footer from "@/components/sections/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        {/* main sections */}
        <main>{children}</main>
        {/* footer */}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
